#!/usr/bin/env python3
"""Materialize the honest marshal-safe macOS test surface.

The macOS hosted runner does not have a Darwin-arm64 Lean seed. Tests which use
``dregg-pq-testkit`` therefore cannot run there: the testkit correctly refuses
to replace the verified cores with the unaudited Rust implementations. Linux's
verified-Lean shards execute the complete suite; this helper keeps the
supplemental macOS lane useful without presenting a predictable process abort
as a product failure or silently narrowing the lane.

The exclusion set is reviewed in ``.github/macos-marshal-test-exclusions.txt``.
Cargo metadata is the authority for the actual direct dev-dependency set, and
the two must match exactly before this script emits package arguments. The
marshal-safe package roots are then partitioned deterministically so the full
surface does not exhaust a single hosted macOS runner.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


TESTKIT = "dregg-pq-testkit"
TIGHT_TIMEOUT_PACKAGES = frozenset(
    {
        "dregg-zkoracle-live",
        "dregg-zkoracle-prove",
        "servo-render",
        "starbridge-tussle",
    }
)


def load_manifest(path: Path) -> set[str]:
    names = {
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    }
    if not names:
        raise ValueError(f"marshal exclusion manifest is empty: {path}")
    return names


def package_sets(metadata: dict[str, Any], expected: set[str]) -> tuple[list[str], list[str]]:
    packages = metadata.get("packages", [])
    names = [package.get("name") for package in packages]
    if not names or any(not isinstance(name, str) or not name for name in names):
        raise ValueError("cargo metadata contained no valid workspace package names")
    if len(names) != len(set(names)):
        raise ValueError("workspace package names are not unique")
    if TESTKIT not in names:
        raise ValueError(f"cargo metadata no longer contains {TESTKIT}")

    actual = {TESTKIT}
    for package in packages:
        for dependency in package.get("dependencies", []):
            if dependency.get("name") != TESTKIT:
                continue
            kind = dependency.get("kind") or "normal"
            if kind != "dev":
                raise ValueError(
                    f"{package['name']} reaches {TESTKIT} as a {kind} dependency; "
                    "the direct-dev-only marshal classifier is no longer sound"
                )
            actual.add(package["name"])

    missing = expected - actual
    unexpected = actual - expected
    if missing or unexpected:
        details = []
        if missing:
            details.append("manifest-only: " + ", ".join(sorted(missing)))
        if unexpected:
            details.append("metadata-only: " + ", ".join(sorted(unexpected)))
        raise ValueError(
            "macOS marshal exclusion drift; review and update the manifest ("
            + "; ".join(details)
            + ")"
        )

    selected = sorted(set(names) - actual)
    excluded = sorted(actual)
    if not selected:
        raise ValueError("macOS marshal-safe package set is empty")
    return selected, excluded


def package_shard(names: list[str], shard_index: int, shard_count: int) -> list[str]:
    """Round-robin the sorted marshal-safe roots into one exact shard."""

    if shard_count < 1:
        raise ValueError("shard count must be positive")
    if shard_index < 0 or shard_index >= shard_count:
        raise ValueError("shard index must satisfy 0 <= index < count")
    selected = [
        name for position, name in enumerate(names) if position % shard_count == shard_index
    ]
    if not selected:
        raise ValueError(f"macOS marshal shard {shard_index}/{shard_count} is empty")
    return selected


def render_nextest_config(selected: list[str]) -> str:
    lines = [
        "# Generated by scripts/ci-macos-marshal-packages.py.",
        "[profile.full]",
        "default-filter = 'all()'",
        'slow-timeout = { period = "60s", terminate-after = 60 }',
    ]
    tight = sorted(TIGHT_TIMEOUT_PACKAGES.intersection(selected))
    if tight:
        selector = " or ".join(f"package({name})" for name in tight)
        lines.extend(
            [
                "",
                "[[profile.full.overrides]]",
                f"filter = '{selector}'",
                'slow-timeout = { period = "30s", terminate-after = 2 }',
            ]
        )
    return "\n".join(lines) + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--metadata", required=True, type=Path)
    parser.add_argument("--exclusions", required=True, type=Path)
    parser.add_argument("--packages-output", required=True, type=Path)
    parser.add_argument("--excluded-output", required=True, type=Path)
    parser.add_argument("--config-output", required=True, type=Path)
    parser.add_argument("--shard-index", required=True, type=int)
    parser.add_argument("--shard-count", required=True, type=int)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    metadata = json.loads(args.metadata.read_text(encoding="utf-8"))
    all_selected, excluded = package_sets(metadata, load_manifest(args.exclusions))
    selected = package_shard(all_selected, args.shard_index, args.shard_count)
    args.packages_output.write_text("\n".join(selected) + "\n", encoding="utf-8")
    args.excluded_output.write_text("\n".join(excluded) + "\n", encoding="utf-8")
    args.config_output.write_text(render_nextest_config(selected), encoding="utf-8")
    print(
        f"macOS marshal shard {args.shard_index + 1}/{args.shard_count}: "
        f"{len(selected)} of {len(all_selected)} test package(s); "
        f"{len(excluded)} verified-PQ package(s) compile-only"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
