#!/usr/bin/env python3
"""Materialize one complete, deterministic Linux nextest package shard.

The hosted Linux runner cannot retain linked test artifacts for all workspace
packages at once: rust-lld eventually faults when its mmap-backed output can no
longer grow.  This helper partitions *workspace roots*, not tests, so Cargo can
build and execute one bounded target tree at a time.  The caller removes the
target tree between shards.

The three packages in ``SPLIT_TARGET_PACKAGES`` are deliberately covered by
the adjacent CI recovery legs instead.  They are the same explicit exclusions
documented in ``ci.yml``: two native cdylibs that cannot link against Lean's
static runtime on ELF, and deos-zed's display-owning application (whose
gpui-free protocol core is tested separately).
"""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path
from typing import Any


SPLIT_TARGET_PACKAGES = frozenset(
    {
        "deos-zed",
        "grain-verify-wasm",
        "starbridge-web",
    }
)

# These packages have diagnosed hang classes and keep the tight timeout from
# the primary nextest policy.  Only names present in the selected shard are
# emitted: nextest treats an out-of-scope package() selector as a hard error.
TIGHT_TIMEOUT_PACKAGES = frozenset(
    {
        "dregg-zkoracle-live",
        "dregg-zkoracle-prove",
        "servo-render",
        "starbridge-tussle",
    }
)


def workspace_package_names(metadata: dict[str, Any]) -> list[str]:
    """Return the unique, sorted generic Linux workspace roots."""

    names = [
        package["name"]
        for package in metadata.get("packages", [])
        if package.get("name") not in SPLIT_TARGET_PACKAGES
    ]
    if not names:
        raise ValueError("cargo metadata contained no generic workspace packages")
    if len(names) != len(set(names)):
        raise ValueError("workspace package names are not unique")
    missing = SPLIT_TARGET_PACKAGES.difference(
        package.get("name") for package in metadata.get("packages", [])
    )
    if missing:
        raise ValueError(
            "the explicit split-target package set drifted: missing "
            + ", ".join(sorted(missing))
        )
    return sorted(names)


def package_shard(names: list[str], shard_index: int, shard_count: int) -> list[str]:
    """Round-robin sorted package roots into an exact zero-based shard."""

    if shard_count < 1:
        raise ValueError("shard count must be positive")
    if shard_index < 0 or shard_index >= shard_count:
        raise ValueError("shard index must satisfy 0 <= index < count")
    selected = [
        name for position, name in enumerate(names) if position % shard_count == shard_index
    ]
    if not selected:
        raise ValueError(f"shard {shard_index}/{shard_count} is empty")
    return selected


def render_nextest_config(selected: list[str]) -> str:
    """Render full-profile coverage with only shard-resolvable overrides."""

    lines = [
        "# Generated by scripts/ci-nextest-shard.py; do not commit generated copies.",
        "[profile.default]",
        'slow-timeout = { period = "60s", terminate-after = 60 }',
        "",
        "[profile.full]",
        "default-filter = 'all()'",
        'slow-timeout = { period = "60s", terminate-after = 60 }',
    ]
    tight = sorted(TIGHT_TIMEOUT_PACKAGES.intersection(selected))
    if tight:
        selector = " or ".join(f"package({name})" for name in tight)
        lines.extend(
            [
                "",
                "[[profile.default.overrides]]",
                f"filter = '{selector}'",
                'slow-timeout = { period = "30s", terminate-after = 2 }',
            ]
        )
    return "\n".join(lines) + "\n"


def load_metadata(path: Path | None) -> dict[str, Any]:
    if path is not None:
        return json.loads(path.read_text(encoding="utf-8"))
    result = subprocess.run(
        ["cargo", "metadata", "--locked", "--no-deps", "--format-version", "1"],
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(result.stdout)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--metadata", type=Path)
    parser.add_argument("--shard-index", required=True, type=int)
    parser.add_argument("--shard-count", required=True, type=int)
    parser.add_argument("--packages-output", required=True, type=Path)
    parser.add_argument("--config-output", required=True, type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    names = workspace_package_names(load_metadata(args.metadata))
    selected = package_shard(names, args.shard_index, args.shard_count)
    args.packages_output.write_text("\n".join(selected) + "\n", encoding="utf-8")
    args.config_output.write_text(render_nextest_config(selected), encoding="utf-8")
    print(
        f"nextest shard {args.shard_index + 1}/{args.shard_count}: "
        f"{len(selected)} of {len(names)} generic packages"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
