#!/usr/bin/env python3
"""Emit a Cargo.lock containing only production-binary dependency reachability."""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path
from typing import Any

PRODUCTION_PACKAGES = {"dregg-cli", "dregg-node"}
LOCK_IDENTITY_FIELDS = {"name", "version", "source", "checksum"}


def parse_lockfile(contents: str) -> dict[str, list[dict[str, str]]]:
    """Parse the package identity fields cargo-audit needs from Cargo.lock."""
    packages: list[dict[str, str]] = []
    current: dict[str, str] | None = None
    for line in contents.splitlines():
        if line == "[[package]]":
            current = {}
            packages.append(current)
            continue
        if current is None or " = " not in line:
            continue
        key, encoded = line.split(" = ", 1)
        if key in LOCK_IDENTITY_FIELDS and encoded.startswith('"'):
            current[key] = json.loads(encoded)
    return {"package": packages}


def reachable_package_ids(metadata: dict[str, Any], roots: set[str]) -> set[str]:
    """Return normal/build dependency closure for named production packages."""
    package_ids = {package["name"]: package["id"] for package in metadata["packages"]}
    missing = sorted(roots - package_ids.keys())
    if missing:
        raise ValueError(f"missing production package(s): {', '.join(missing)}")

    nodes = {node["id"]: node for node in metadata["resolve"]["nodes"]}
    pending = [package_ids[name] for name in sorted(roots)]
    reachable: set[str] = set()
    while pending:
        package_id = pending.pop()
        if package_id in reachable:
            continue
        reachable.add(package_id)
        for dependency in nodes[package_id]["deps"]:
            kinds = dependency.get("dep_kinds", [])
            if any(kind.get("kind") != "dev" for kind in kinds):
                pending.append(dependency["pkg"])
    return reachable


def quoted(value: str) -> str:
    return json.dumps(value)


def render_lockfile(metadata: dict[str, Any], lockfile: dict[str, Any]) -> str:
    reachable = reachable_package_ids(metadata, PRODUCTION_PACKAGES)
    packages_by_key = {
        (package["name"], package["version"], package.get("source")): package
        for package in lockfile["package"]
    }
    selected = []
    for package in metadata["packages"]:
        if package["id"] not in reachable:
            continue
        key = (package["name"], package["version"], package.get("source"))
        try:
            selected.append(packages_by_key[key])
        except KeyError as error:
            raise ValueError(f"reachable package missing from Cargo.lock: {key}") from error

    lines = ["# Generated by scripts/production_audit_lock.py; do not commit.", "version = 4", ""]
    for package in sorted(selected, key=lambda item: (item["name"], item["version"], item.get("source", ""))):
        lines.extend(["[[package]]", f"name = {quoted(package['name'])}", f"version = {quoted(package['version'])}"])
        if source := package.get("source"):
            lines.append(f"source = {quoted(source)}")
        if checksum := package.get("checksum"):
            lines.append(f"checksum = {quoted(checksum)}")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--target", default="x86_64-unknown-linux-gnu")
    args = parser.parse_args()

    metadata = json.loads(
        subprocess.check_output(
            [
                "cargo",
                "metadata",
                "--format-version",
                "1",
                "--locked",
                "--filter-platform",
                args.target,
            ],
            text=True,
        )
    )
    lockfile = parse_lockfile(Path("Cargo.lock").read_text())
    args.output.write_text(render_lockfile(metadata, lockfile))


if __name__ == "__main__":
    main()
